### ISSUE TITLE
Redirect to /live/profile/settings doesn't work

### ISSUE THREAD

**Issue by InsanityMatrix** [InsanityMatrix/SocialFoot#1]
Can't tell what is causing the problem, to fix later.

Error Returned by Log:
`
2020-02-08T18:01:15.994873+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/live/profile/settings" host=socialfoot.herokuapp.com request_id=ccf60767-bfd9-4551-9754-138ef46f4d39 fwd="184.170.167.136" dyno=web.1 connect=1ms service=16ms status=503 bytes=0 protocol=https
2020-02-08T18:01:15.995014+00:00 app[web.1]: 2020/02/08 18:01:15 http: panic serving 10.109.220.238:16493: runtime error: invalid memory address or nil pointer dereference
2020-02-08T18:01:15.995045+00:00 app[web.1]: goroutine 41 [running]:
2020-02-08T18:01:15.995046+00:00 app[web.1]: net/http.(*conn).serve.func1(0xc0001e23c0)
2020-02-08T18:01:15.995048+00:00 app[web.1]: /app/tmp/cache/go1.12.12/go/src/net/http/server.go:1769 +0x139
2020-02-08T18:01:15.995048+00:00 app[web.1]: panic(0x7fafc0, 0xbcfff0)
2020-02-08T18:01:15.995048+00:00 app[web.1]: /app/tmp/cache/go1.12.12/go/src/runtime/panic.go:522 +0x1b5
2020-02-08T18:01:15.995049+00:00 app[web.1]: main.profileSettingsHandler(0x903820, 0xc0002241c0, 0xc00021ea00)
2020-02-08T18:01:15.995050+00:00 app[web.1]: /tmp/tmp.IMbfOx0v7R/.go/src/github.com/InsanityMatrix/SocialFoot/main.go:226 +0x326
2020-02-08T18:01:15.995051+00:00 app[web.1]: net/http.HandlerFunc.ServeHTTP(0x88a858, 0x903820, 0xc0002241c0, 0xc00021ea00)
2020-02-08T18:01:15.995051+00:00 app[web.1]: /app/tmp/cache/go1.12.12/go/src/net/http/server.go:1995 +0x44
2020-02-08T18:01:15.995052+00:00 app[web.1]: github.com/InsanityMatrix/SocialFoot/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d20c0, 0x903820, 0xc0002241c0, 0xc00021e800)
2020-02-08T18:01:15.995053+00:00 app[web.1]: /tmp/tmp.IMbfOx0v7R/.go/src/github.com/InsanityMatrix/SocialFoot/vendor/github.com/gorilla/mux/mux.go:210 +0xe3
2020-02-08T18:01:15.995053+00:00 app[web.1]: net/http.serverHandler.ServeHTTP(0xc0001e01a0, 0x903820, 0xc0002241c0, 0xc00021e800)
2020-02-08T18:01:15.995054+00:00 app[web.1]: /app/tmp/cache/go1.12.12/go/src/net/http/server.go:2774 +0xa8
2020-02-08T18:01:15.995054+00:00 app[web.1]: net/http.(*conn).serve(0xc0001e23c0, 0x904160, 0xc00019c700)
2020-02-08T18:01:15.995054+00:00 app[web.1]: /app/tmp/cache/go1.12.12/go/src/net/http/server.go:1878 +0x851
2020-02-08T18:01:15.995055+00:00 app[web.1]: created by net/http.(*Server).Serve
2020-02-08T18:01:15.995055+00:00 app[web.1]: /app/tmp/cache/go1.12.12/go/src/net/http/server.go:2884 +0x2f4
`

**Comment by InsanityMatrix** [comment]
Fixed, this was a multitude of issues.
First what the actual database query, it was pulling with the wrong info.
Then with the values being passed in referencing nil or wrong types.  And then there was the verification issue where it altered values and didn't work in the query

But the redirect was in fact working
